# Generated by Django 3.1.4 on 2020-12-30 06:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoNewApp', '0003_auto_20201219_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='message',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
